### ISSUE TITLE
RLogin sending just first character of Username

### ISSUE THREAD

**Issue by KenDB3** [klamonte/qodem#10]
Hi there! You've done an awesome job on this. I replied back to you on DOVE-Net but figured I would put it here as well in case it gets lost in the shuffle over on DOVE-Net.

I have been connecting over SSH and it works really well. I tried connecting
over RLogin, and my BBS started a New User Signup because it saw the username
passed as "K" instead of "Kendb3". 

I am not sure if this is a problem with Qodem or the far end which is my BBS running Synchronet, so you may need to compare to some other systems that allow for RLogin.

**Comment by klamonte** [comment]
Just put a new Windows setup out.  Does this one work for you?

http://qodem.sourceforge.net/qodem-1.0beta-preview-setup.exe

**Comment by KenDB3** [comment]
I tested it out. It did the trick! Well done!

**Comment by klamonte** [comment]
Awesome!  Closing.
