### ISSUE TITLE
VGA font - Some Font Sizes have a Gap in Drawing Characters

### ISSUE THREAD

**Issue by KenDB3** [klamonte/qodem#11]
This one is low level. At first I thought it was all font sizes or maybe bigger font sizes, but it is just some. Using the VGA font, I noticed with certain font sizes there seems to be tiny gaps on the edge of some of the block drawing characters in CP437. 
This gap disappears if I choose a font size of 11, 13, 18, 19, 23, or 24.
I am using Windows 8.1 (64-bit), 1920x1080 resolution.

Examples:
shows gap
http://kendibattista.net/photos/qodem/Screen1-10-pt-font.png
http://kendibattista.net/photos/qodem/Screen2-10-pt-font.png
http://kendibattista.net/photos/qodem/Screen3-10-pt-font.png
shows gap
http://kendibattista.net/photos/qodem/Screen1-20-pt-font.png
http://kendibattista.net/photos/qodem/Screen2-20-pt-font.png
http://kendibattista.net/photos/qodem/Screen3-20-pt-font.png
gap disappears
http://kendibattista.net/photos/qodem/Screen1-24-pt-font.png
http://kendibattista.net/photos/qodem/Screen2-24-pt-font.png
http://kendibattista.net/photos/qodem/Screen3-24-pt-font.png

**Comment by klamonte** [comment]
I think I'm ready to close this one.  Would you be comfortable with that?

The best I can do is direct people to Terminus or uni_vga.

**Comment by KenDB3** [comment]
That's perfectly fine, Kevin. I say go for it.
