### ISSUE TITLE
Missing cw3230mt.DLL (Windows 8.1 64-bit)

### ISSUE THREAD

**Issue by veganaize** [klamonte/qodem#12]
After install (followed by a reboot) of qmodem1.0beta, I receive an error:
"The program can't start because cw3230mt.DLL is missing from your computer."

**Comment by veganaize** [comment]
http://cboard.cprogramming.com/windows-programming/8721-borland-cc3250mt-dll.html

**Comment by klamonte** [comment]
Doh!  I let the InnoSetup pick up the Borland exe instead of the VC exe.  Should be fixed now.

**Comment by klamonte** [comment]
Please close if you are no longer seeing this problem with the 1.0beta release.

**Comment by veganaize** [comment]
Beautiful.
