### ISSUE TITLE
This project is great :')

### ISSUE THREAD

**Issue by AaronFriel** [klamonte/qodem#13]
I've followed this for a while, and I think it's awesome to see this tribute to what my dad did.

P.S.: I'm sending him a link to this repository, he's still doing software development, he'll get a kick out of building this project.

**Comment by klamonte** [comment]
Aw thanks! :)

I keep hoping to find some time to swing by his neck of the woods and take him out to dinner.  Back in '92 or so, Qmodem was my link to a huge wide world and changed my life for the better.

**Comment by klamonte** [comment]
Thank you for this encouragement last year.  After a user managed to successfully dial several BBSes recently, I finally cut the 1.0.0 release. :)
