### ISSUE TITLE
Be able to run as a fully portable application

### ISSUE THREAD

**Issue by klamonte** [klamonte/qodem#38]
We need several things:
1. A --config command line option to read qodemrc from user-supplied file.  If given, NO OTHER option file locations are read.
2. Be able to load and run phonebook, scripts, modem cfg, color cfg, keyfiles, etc. from read-only media.  The media is checked for write access, and if not found save operations fail with a notification.  If script_stderr cannot be created, scripts are disabled for that session.
3. A --read-only command line option that disables all save operations entirely.  This will require some re-work for config files that auto-create themselves.  Also:
   - script_stderr cannot be created hence scripts are disabled on POSIX.
   - host mode uploads are disabled.
   - downloads and zmodem/kermit autostart are disabled.
   - session log, capture, screen dump, and scrollback save are disabled.

**Comment by gitlarryf** [comment]
Kevin?  I worked at MSI during the development of Qmodem, and wondered if 
you would be interested in any of my help in the development of qodem? 
And also wondered if you had any plans to support the "Qmodem Pro for Win 
95" style application (a GUI, really...), and if you might be interested 
in the ability to cross-compile, and/or execute original Qmodem script 
code...  I may be able to help in that area...

Larry

**Comment by klamonte** [comment]
@gitlarryf Hi Larry,

I would be delighted if anyone wanted to poke on Qodem.  Pull requests would be ideal, but patches would be fine too.  The code is now public domain too, so if you even wanted to make a commercial closed-source version based on what is here that is OK.

I have no plans right now to develop a GUI-style Qodem, but it could be done without too much hassle (just very very tedious).  The code-heavy hard parts -- scrollback, emulation, connection protocols, and transfer protocols -- are pretty modular and could be dropped into a new GUI framework.  I have even transliterated the VT100/220/Linux/xterm emulation to Java as jexer.tterminal.ECMA48 over at https://github.com/klamonte/jexer .  (Kermit is in the works, no ETA yet.)  The form screens (phonebook, dialogs, etc.) would be a lot of work to re-create as GUI dialogs though.

Being able to execute Qmodem script would be really interesting!  I had a language and compiler in mind for a long while but could never get the hang of it enough to really start on it, nor was I able to figure out a nice way to execute script commands or drive a mini-VM/interpreter.  So I sort of cheated by taking my idea for external protocols and making that support scripts instead, which was nice but different too.

The only bad news is that after 1.0.0 comes out this summer I will be scaling back my hobby programming time for a while.  I have some personal life items that have been too long waiting to deal with, and want to get Qodem into a good place before I reduce my efforts.

**Comment by 3FLLC** [comment]
My company too would like to get involved and contribute to the evolution of qodem - our owner used to develop QuickBBS 2.6 and later, along with owning 12th largest ISP in US, and developing a new product he calls "Version 2 BBS" technology. (ANSI, Avatar, VT100/220, X11, HTML5 user interface).
