### ISSUE TITLE
v1.0beta Mac OSX bug report

### ISSUE THREAD

**Issue by 3FLLC** [klamonte/qodem#40]
1. Alt keystroke is not being detected.
2. Mouse does not interact with display (e.g. cannot copy/paste)
3. Default X-UTF8 connection to BBS sends CR, LF on ENTER (all other terminals tested send CR only) - revising BBS software to handle this.

**Comment by klamonte** [comment]
Thanks for reporting this.  I will see if I can reproduce and fix.

Which version of OSX are you using?

**Comment by klamonte** [comment]
I've seen point 3 on this list, when using a telnetd server that switches back to ascii (WONT/DONT binary mode).  Should have a fix in 1.0.0-dev shortly.

**Comment by tssva** [comment]
In OSX terminal by default the Option/Alt key is not the Meta key by default. If using OSX's Terminal app you need to enable "Use Option as Meta key" in the keyboard section of your terminal profile. If you are using an international keyboard you will lose the ability to enter certain symbols. If you are using iTerm2 you want to go to the keys section of your terminal profile and select "Left option key acts as: +Esc" and/or "Right option key acts as: +Esc". If you have an international keyboard assigning only one to +Esc will allow you to use the other to enter symbols which don't appear on your keyboard. 

Qodem intercepts all mouse actions which prevents normal mouse selection for cut & paste. If you are using OSX's terminal pressing the fn key while using the mouse will prevent reporting of mouse events to the terminal and allow you to make selections with the mouse. If using iTerm2 the same can be achieved by pressing the Option key while making a selection or "Enable mouse reporting" can be turned off in the Terminal section of your profile settings. It might also be a good idea for qodem to make mouse support configurable.

**Comment by 3FLLC** [comment]
@tssva great reply!

**Comment by klamonte** [comment]
Are you comfortable if I close this?

**Comment by 3FLLC** [comment]
Yes, thank you … I will reinstall everything again and try it against the systems I have setup.

**Comment by klamonte** [comment]
Thanks!
