### ISSUE TITLE
C64: Petscii Support

### ISSUE THREAD

**Issue by pcollins2001** [klamonte/qodem#41]
Petscii Support would be great.
So, you could dialing C64 BBS with qodem.

**Comment by klamonte** [comment]
PETSCII would be cool indeed!  If I add it, I'd like to do it well.  Converting the glyphs to Unicode should be straightforward, but I'll need to do some research on the rest of it.  Were C64 BBSes always 40 col?  Were the cursor movement PETSCII honored as well as the colors?  Etc.

Is there a terminal out there that does C64 BBSes "the right way" that I could use as reference?

**Comment by pcollins2001** [comment]
List of C64 BBS: http://cbbsoutpost.servebbs.com/
PC/Linux/Mac C64 Terminal Emulator: https://paradroid.automac.se/cgterm/

**Comment by klamonte** [comment]
Colors are not perfect, and it is still very new and probably buggy, but PETSCII support is now formally in the master branch.
