### ISSUE TITLE
clang compiler support

### ISSUE THREAD

**Issue by klamonte** [klamonte/qodem#43]
Modern clang on OSX has several errors:
- miniupnpc / minissdpc.c is missing headers for close(), write(), and read().
- colors.c warnings due to 8-bit encoding.  Either switch to UTF-8 or pass -Wno-invalid-source-encoding .
- kermit.c and xmodem.c snprintf() off_t is long long rather than unsigned long.
- phonebook.c several enum comparisons to -1 are tautological.
- protocols.c sprintf() %Lu is undefined or has no effect.

Test against modern clang on Linux and try to find a recent OSX to do the same.

**Comment by klamonte** [comment]
#39 make-log.txt shows the errors.

**Comment by tssva** [comment]
Compiles properly on macOS Sierra with clang-800.0.42.1 (latest).

**Comment by klamonte** [comment]
Worked for me too on Sierra.  Closing.
