### ISSUE TITLE
Compiling Issue on Raspberry Pi3 Raspbian

### ISSUE THREAD

**Issue by shift838** [klamonte/qodem#51]
I am attempting to compile Qodem 1.0 Beta for the latest version of Raspbian for my Pi3.

Here are some of the last lines before it errors at the bottom:

gcc -DHAVE_CONFIG_H -I. -I./source  -I. -I.   -g -O2 -DQ_NO_NEWTERM -DQ_SSH_CRYPTLIB -Ilib/cryptlib -DQ_UPNP -Ilib/upnp -MT source/translate.o -MD -MP -MF $depbase.Tpo -c -o source/translate.o source/translate.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo source/vt100.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I./source  -I. -I.   -g -O2 -DQ_NO_NEWTERM -DQ_SSH_CRYPTLIB -Ilib/cryptlib -DQ_UPNP -Ilib/upnp -MT source/vt100.o -MD -MP -MF $depbase.Tpo -c -o source/vt100.o source/vt100.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo source/vt52.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I./source  -I. -I.   -g -O2 -DQ_NO_NEWTERM -DQ_SSH_CRYPTLIB -Ilib/cryptlib -DQ_UPNP -Ilib/upnp -MT source/vt52.o -MD -MP -MF $depbase.Tpo -c -o source/vt52.o source/vt52.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo source/xmodem.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I./source  -I. -I.   -g -O2 -DQ_NO_NEWTERM -DQ_SSH_CRYPTLIB -Ilib/cryptlib -DQ_UPNP -Ilib/upnp -MT source/xmodem.o -MD -MP -MF $depbase.Tpo -c -o source/xmodem.o source/xmodem.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo source/zmodem.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I./source  -I. -I.   -g -O2 -DQ_NO_NEWTERM -DQ_SSH_CRYPTLIB -Ilib/cryptlib -DQ_UPNP -Ilib/upnp -MT source/zmodem.o -MD -MP -MF $depbase.Tpo -c -o source/zmodem.o source/zmodem.c &&\
mv -f $depbase.Tpo $depbase.Po
gcc  -g -O2 -DQ_NO_NEWTERM -DQ_SSH_CRYPTLIB -Ilib/cryptlib -DQ_UPNP -Ilib/upnp
 -o qodem source/ansi.o source/avatar.o source/codepage.o source/colors.o source/common.o source/console.o source/dialer.o source/emulation.o source/field.o source/forms.o source/help.o source/host.o source/input.o source/kermit.o source/keyboard.o source/modem.o source/music.o source/netclient.o source/options.o source/phonebook.o source/protocols.o source/qodem.o source/screen.o source/script.o
source/scrollback.o source/states.o source/translate.o source/vt100.o source/vt52.o source/xmodem.o source/zmodem.o  -lncursesw -lutil  lib/cryptlib/libcl.a -lpthread lib/upnp/libminiupnpc.a
gcc: error: lib/cryptlib/libcl.a: No such file or directory
Makefile:635: recipe for target 'qodem' failed
make[1]: *** [qodem] Error 1
make[1]: Leaving directory '/home/pi/Downloads/qodem-1.0beta'
Makefile:782: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by klamonte** [comment]
Thank you for the issue report.

It looks like cryptlib is failing to compile.  Do you have the full compile log?

To get this compile working right now, you can pass --disable-ssh to configure so that it doesn't try to use cryptlib.  Or you can use 'make -f build/Makefile.generic' to get a working binary in bin/qodem.

**Comment by shift838** [comment]
thanks!  I got it compiled with the 'make -f build/Makefile.generic' command.

looks pretty good connecting to my retro BBS too..

**Comment by klamonte** [comment]
Are you comfortable with me closing this issue?
