### ISSUE TITLE
Switching from a SSL (internal or external) connection to internal Telnet causes hang + crash

### ISSUE THREAD

**Issue by lholden** [klamonte/qodem#66]
This happens in either the 1.0.0 released version or the 1.0.1 branch.

1) use_external_telnet = false
2) connect to a BBS over SSL (either using the built in SSL client or an external client)
3) hang up the connection
$ Trying to connect to a telnet BBS after the above, qodem will display "Connecting to xyz...." until the cycle timer runs out... at which point it will repeat trying to connect just continue spinning.

If you hit K it will stop trying as expected (but the issue remains). If you hit ESC, qodem crashes on 1.0.0. The 1.0.1 will not crash in this case. 

If you exit qodem and then immediately connect to the telnet BBS it works without issue. If you change "use_external_telnet = true" then it works without issue.

If you switch qodem 1.0.1 to use_external_ssh=true and try to repeat the above, it crashes immediately after trying to connect to the telnet BBS.

I am using Fedora 25 and the Gnome Terminal for this.

**Comment by klamonte** [comment]
Thanks for reporting this.  I will try to replicate this weekend.

**Comment by klamonte** [comment]
This seems to work, but will require much more extensive testing before I can be comfortable calling it done.  Need to test a lot more with remote closing vs hangup vs nice close, and then serial vs shell vs network.

**Comment by lholden** [comment]
Fantastic. I'll rebuild and let you know if I have any issues. :)

**Comment by lholden** [comment]
Qodem is great btw. I am very happy that it exists and is being maintained! :D

**Comment by lholden** [comment]
One more bug for you! It seems related, so I figured I'd just leave it here. Connecting via SSH, logging out of the bbs, and then dialing into a telnet system seems to work fine now... with one exception.

If you connect to a system using the *internal* SSH client, then explicitly hang up the connection (alt+h) (rather than logging out), then trying to connect to *any* system via any means causes a crash. (including reconnecting to the same bbs). 

```
qodem: source/netclient.c:997: net_connect_start: Assertion `connected == Q_FALSE' failed.

Aborted (core dumped)
```
