### ISSUE TITLE
Pasting text inserts extra characters before and after pasting.

### ISSUE THREAD

**Issue by lholden** [klamonte/qodem#67]
This is using Fedora 25 and Gnome Terminal.

When pasting into qodem, it seems like the pasted content is prefixed and suffixed with extra data. When pasting into a field of the directory for example... qodem will display a space before and after the pasted text. (e.g. pasting a user name or password).

When pasting into a connected BBS it displays a ? before and after the text. If bracketed paste mode is enabled, instead of ? qodem will display ~ instead.

**Comment by klamonte** [comment]
Thanks for reporting this.  I've for a Fedora VM around and will be able to test it later this weekend.  Curious to see it this happens under vanilla xterm too.  Is your gnome-terminal using bracketed paste mode?

**Comment by lholden** [comment]
Hmm. To be honest with you I am not sure how one would check that. I believe one would have to adjust readline. So... I've tried to explicitly disablee/enable it with the bind command to see if it made any difference... it didn't. (bind 'set enable-bracketed-paste off')

**Comment by klamonte** [comment]
I was able to replicate.  Thanks for catching this, I should have seen at the time that I added bracketed paste support.
