### ISSUE TITLE
Command line options not working as expected

### ISSUE THREAD

**Issue by jordemort** [klamonte/qodem#68]
Hey, ran into a couple of issues while playing with qodem. I'm willing to work with you to debug them, since I'd like to use qodem to provide era-accurate ANSI emulation for https://github.com/jordemort/hodoor

`--connect-method` doesn't seem to work at all for me, it just always tries to ssh to whatever I pass to `--connect`

When executing a command like `qodem --emulation ANSI --codepage CP437 --status-line off -x bash`, at least `--emulation` and possibly `--codepage` don't seem to be honored, and `TERM` is not set/changed in the environment.

**Comment by jordemort** [comment]
Forgot to mention; using the 1.0 amd64 deb from sourceforge on Ubuntu 16.04

**Comment by klamonte** [comment]
Thanks for this report.  Looks like my code for --xterm broke --connect-method, let's see what else needs fixing...

**Comment by jordemort** [comment]
Hey, wanted to let you know that I built the `1.0.1-dev` branch the other day and things now seem to work as expected there

**Comment by klamonte** [comment]
Awesome, thanks!
