### ISSUE TITLE
Configure doesn't work

### ISSUE THREAD

**Issue by danger89** [klamonte/qodem#70]
Hi,

I'm try to build it using the ./configure and make command under Debian Jessie Linux. But only ./configure will end up with "Cannot find input file 'Makefile.in'. So only the following DOES works:

`libtoolize --copy --force && automake --add-missing --copy && autoconf && ./configure`

My suggestion would be the improve the [INSTALL](https://github.com/klamonte/qodem/blob/master/INSTALL) file?

Kind regards,
Melroy

**Comment by klamonte** [comment]
Thanks for this report, I've added text to INSTALL to mention autogen.sh or a more explicit command to generate an autoconf build from source repo.
