### ISSUE TITLE
Should support "control" key when on macOS as alternate to CTRL.

### ISSUE THREAD

**Issue by ispyhumanfly** [klamonte/qodem#71]
First, I love this client. I used Qmodem back in the day, and, I simply love what you've done with this. I also dig how it works within a terminal, and, leverages a terminal instance itself. A significant step up from SyncTerm in this regard. Well done. 

I would like to contribute to this project. 

I'd like to provide a bit better support for macOS. Honestly, at present I'm noticing that I use "control" key in the shell, doesn't work. 

What are your thoughts and where could I poke around to perhaps aid in this? 

Thanks!

_dan

**Comment by klamonte** [comment]
Thanks for the positive feedback!  Qmodem was my window to the world in the early 90's, and it's been a long journey figuring out "how did he DO that?" :)

On the macOS question, the main thing is to see a) is control-<char> emitting any output to the shell at all, and 2) what is that output?  Easiest way to check is to do 'cat', type some stuff and see if it echoes anything back.  If that doesn't work, you might be able to to 'cat > filename', type stuff, and then hexdump that filename to see what was produced.  Looking around, it seems that some terminals on Mac (e.g. iTerm) have had issues in the past with not sending control keys on.

Qodem's actual input handling is qodem_win_getch() in input.c.  Around line 2275 it has a check that it uses for control characters (everything under hex 0x20), and sets a KEY_FLAG_CTRL accordingly.  This is the "normal" way to detect control characters, they are just the first 32 bytes in ASCII.  (This function is one of the relatively few OMG monster functions, as it has branches for handling input in both ncurses and PDcurses, and will also call out to parse ncurses sequences and extended xterm codes...)

Is there a particular terminal that is having trouble with CTRL?  I might be able to dig in a bit sometime next month.

**Comment by klamonte** [comment]
Moving to GitLab...
