### ISSUE TITLE
RFE: Use CMake for better cross platform building?

### ISSUE THREAD

**Issue by hobbes1069** [klamonte/qodem#72]
I don't have a ton of spare cycles but in my experience CMake works much better than autotools or manual makefiles to support building on multiple platforms. It can even generate VS project files. 

I'd like to gauge interest before putting any real effort into it.

**Comment by klamonte** [comment]
A PR for CMake would certainly be welcomed, especially if it helps the Windows folks.  If it turns out to be your preferred build system for RPM then I would be happy to move those to CMake too.

**Comment by hobbes1069** [comment]
It may take me a while but I'll submit something when I get it working.

**Comment by hobbes1069** [comment]
If you want to check out my fork, I have basic building working. Need to integrate PDCurses. I've also stubbed out some MinGW stuff that may be able to obsolete some of the windows dependedies in the future.

https://github.com/hobbes1069/qodem/tree/cmake

**Comment by klamonte** [comment]
Moving to GitLab...
