### ISSUE TITLE
Petscii Mode: Delete Key doesnt work

### ISSUE THREAD

**Issue by soenkesmiletzki** [klamonte/qodem#76]
If I call a C64 Board like "rapidfire.hopto.org:64128" i couldnt use the Delete Key to correct some Text.
The Prompt doesnt go back to delete the Letter.

**Comment by klamonte** [comment]
Thanks for reporting this.  It will be a little while until I can test and fix it, but I will get to it eventually.  (Apologies on the delays, I just moved across the country and most of my stuff is still in boxes.)

**Comment by klamonte** [comment]
Moving to GitLab...
