### ISSUE TITLE
Qodem (Win10) crashes when using serial port VT220 connection

### ISSUE THREAD

**Issue by AIWIndustries** [klamonte/qodem#77]
When I use Qodem via serial to ethernet convertor and run VT220 via IP connection I have no issues at all. When I switch and try to establish a VT220 connection via serial port Qodem crashes. Has anyone else experienced this issue?

**Comment by AIWIndustries** [comment]
Just so you know it isn't the incoming data....i am able to run the vt220 emulation in TeraTerm and Hyperterminal.  I prefer to use Qodem cause when I used it via IP connection it does a much better job of providing full screen optimization. The others just make a small display inside an expanded window.

**Comment by klamonte** [comment]
You aren't doing anything improper, Qodem has the crash.  Qodem's Win32 serial port is very lightly tested alas, I haven't had a Windows box with a real serial port in a while so I have been testing in VMs.  I will see if I can find out how it is crashing for you.

**Comment by AIWIndustries** [comment]
I’m using a silicon labs CP2104 based USB to DB9 serial adapter.

I have an old XP box with a real DB9 serial port. I’ll try that to ensure it isn’t something within the adapter causing the issue.

**Comment by NWS-NRC** [comment]
XP with built in COM1 on motherboard crashed as well.

**Comment by klamonte** [comment]
Thank you for testing it on XP.  I have a Windows 7 box in the garage with a real serial port, when I get a chance I will check it out.

(Sorry for not being able to jump on this, I just moved out of state and am still setting up the new home.)

**Comment by AIWIndustries** [comment]
Have you been able to take a look at this? In the meantime I was able to figure out that even though not well documented, Putty will run vt220 over serial with the proper configuration. I do prefer Qodem though because in a linux environment it doesn't require an xserver to run a window. Qodem can run at boot seemlessly on a Pi.

**Comment by klamonte** [comment]
I have not yet been able to look into this, sorry.

**Comment by klamonte** [comment]
Moving to GitLab...
