### ISSUE TITLE
qodem zmodem download speed

### ISSUE THREAD

**Issue by mtatton** [klamonte/qodem#79]
First I wanted to thank You for such a great program that's qodem.
I really enjoy using it. By now I tried to download large file using
z-modem. The speed it downloads is cca 14000 cps compared to
18,2 mio cps in SyncTerm on the same machine, same line, same
conditions. Thanks in advance for any response.

**Comment by klamonte** [comment]
Sorry I missed this report for so long, been catching up on the backlog.

Which OS are you using Qodem in?  Is this on Windows?  I ask because Qodem's overall event loop in Windows is different, and that might explain things.

**Comment by mtatton** [comment]
Thank You for Your response. It was on Linux. It was using Z-Modem standard. I can reproduce it again right now. The first file downloads fast. But during the transfer of second file the transfer speeds falls down dramatically. 
This is what is in the window:
Synchronet External X/Y/ZMODEM  v2.0-Linux  Copyright 2016 Rob Swindell

Output buffer size: 16384
No socket descriptor specified, using STDIO

I'm using the qodem-1.0.1-dev branch cloned on 21th February 2019.

Let me know if You would need any additional information. I'll meanwhile retry on different board.

Thank You for Your effort

**Comment by mtatton** [comment]
P.S. on another Board it works just fine. I consider this as an problem in certain situation that isn't caused by qodem. Thank You & closing.
