### ISSUE TITLE
No Filetransfer with C64 BBS 

### ISSUE THREAD

**Issue by profundusgmbh** [klamonte/qodem#85]
I try to upload/download some files to a c64 BBS, but it doesnt work, using Petscii Mode.
I try any kind of fileprotocoll like xmodem, xmodem1k, xmodemcrc but no upload or download.

I compilied qodem at clearlinux and everthing looks ok, only filetransfer doesnt work.
So, i try to upload/download at a other pc with windows10, but some result: No Filetransfer working... 

Any Idea? Bug?
Let me know if you need a C64 BBS for testing..

**Comment by klamonte** [comment]
Thanks for reporting this.  Is this happening with multiple C64 BBSes, or just some specific hosts?  If you could point me to one that is failing, I can see what I can find out.

**Comment by klamonte** [comment]
Moving to GitLab...
