### ISSUE TITLE
Configure needs Makefile.in

### ISSUE THREAD

**Issue by artlogic** [klamonte/qodem#86]
When I run `./configure` I receive the following error:

```config.status: error: cannot find input file: `Makefile.in'```

Most projects include this file, but it's being ignored in .gitignore for this project. Once the file is generated `./configure` runs just fine. I generated the file by running:

```
aclocal
automake --add-missing
```

I'm happy to submit a PR if that helps, but I'm not an automake expert, so it could be there's something I'm missing here.

**Comment by klamonte** [comment]
When pulling from git, autogen.sh will make Makefile.in.

I'll add some text to the README and INSTALL to mention this better.

**Comment by artlogic** [comment]
One question about that: if you include Makefile.in, then the end user wouldn't need automake to be installed - correct? I do see a lot of projects that include this file, but I can confirm that autogen.sh does the trick too.

**Comment by klamonte** [comment]
If I included Makefile.in, then users who pull directly from git could run configure, yes.  I used to have it in actually and not care about it, but someone came along with autogen.sh and convinced me at the time that it was better in the long run not to have build artifacts.  But then here I am with configure in there anyway, so may as well include Makefile.in too.

Just merged this into master, along with the most recent minor things I've seen.  See if this works for you.

**Comment by artlogic** [comment]
Works great and definitely matches my experience with other software projects.

One odd thing I noticed that may be unrelated: when I run `make` after running `./configure`, it runs `./configure` again (the first time). I've never seen that before - is there a reason?

**Comment by klamonte** [comment]
I've seen that when pulling directly from git (and in the old days cvs) in the first few minutes.  I've chalked it up to the timestamps being skewed between my machine and the code repo machine.  After a few minutes everything sorts itself out with all of the build artifacts having more recent timestamps than whatever came out of the repo.

**Comment by artlogic** [comment]
Huh... not something I've seen before, but I'm definitely no autotools expert. Thanks for making things a little easier to build!
