### ISSUE TITLE
HiDPI

### ISSUE THREAD

**Issue by synacktic** [klamonte/qodem#91]
I love qodem, but it does not seem to scale well on HiDPI screens. I am using the largest font I can (-*-terminus-medium-r-normal--32-320-*-*-c-*-iso10646-1), and it is usable, but if my resolution was any higher, it would not be.  This may be an issue with PDCurses and I'm unsure if later versions of it fix this issue under X11.

**Comment by klamonte** [comment]
This is mainly an issue with qodem-x11, right?  I haven't looked at PDCurses in a long while, but at the time I integrated it with qodem it only supported bitmap fonts.  I'll go poke in PDcurses again in a bit and see what's going on there.

**Comment by klamonte** [comment]
Moving to GitLab...
