### ISSUE TITLE
source/host.c: 2 * suspicious for loop ?

### ISSUE THREAD

**Issue by dcb314** [klamonte/qodem#92]
source/host.c:1032:13: warning: variable 'message_i' is incremented both in the loop header and in the loop body [-Wfor-loop-analysis]
source/host.c:1244:13: warning: variable 'message_i' is incremented both in the loop header and in the loop body [-Wfor-loop-analysis]

**Comment by klamonte** [comment]
I believe the code is correct, and it is skipping past the '.' message separators.  I will check a bit more, and either fix if it's a bug or add comments about its intent.
