### ISSUE TITLE
Core dump when killing a connection

### ISSUE THREAD

**Issue by cardpuncher** [klamonte/qodem#94]
Hi,

When dialing a number, if I kill the connection by pressing K, I always get a core dump with the following error message:

<code>qodem: source/modem.c:2567: close_serial_port: Assertion `q_child_tty_fd != -1' failed.

Aborted (core dumped)</code>

I tried with two modems (a <a href="https://www.startech.com/en-us/networking-io/usb56kemh2">Startech.com USB V.92 modem</a> and a <a href="https://www.usr-emea.com/support/s-product-template.asp?loc=unkg&prod=5630g">US Robotics 5630G</a> which is connected via a serial to USB adapter) and got the same result. The BBS number called doesn't make a difference.

The screenshot below may give a better idea (the blinking cursor disappears after the crash).
![qodem](https://user-images.githubusercontent.com/64688741/137978861-1e233bf6-55cf-4eff-9e9f-f3c5337dcbe9.gif)

This is happening under Ubuntu 20.04.3 within MATE Terminal, and qodem --version returns 
$ qodem --version
qodem version 1.0.1
Written 2003-2021 by Autumn Lamonte ⚧ Trans Liberation Now

Thank you for such a well documented program.

**Comment by klamonte** [comment]
Thank you for reporting this.

This should hopefully avoid the assertion for you.  You'll have to pull from git and compile.

The bad news is that zero of my computers at home have serial ports now, or Windows, so it is hard to really test. :(

**Comment by cardpuncher** [comment]
On 23.01.2022 02:45, Autumn Lamonte wrote:
> Thank you for reporting this.
> 
> This should hopefully avoid the assertion for you. You'll have to pull 
> from git and compile.
> 
> The bad news is that zero of my computers at home have serial ports now, 
> or Windows, so it is hard to really test. :(

I downloaded the tarball from 
<https://github.com/klamonte/qodem/archive/refs/heads/master.tar.gz> and 
compiled it. Killing a connection doesn't result in code dump anymore, 
thank you!

I think you can happily close this report.

**Comment by klamonte** [comment]
Thank you!
